version: "3"
services:
  sub:
    build:
      context: .  # Docker context from folder of this file; needed to include requirement.txt
      dockerfile: ./sub/Dockerfile
    ports:
      - "5550:5550"  # map container interal 5550 port to publicly accessible 5550 port
    stdin_open: true  # same as docker -i (interactive)
    tty: true  # same as docker -t (tty); see if sub actually receives pub messages
  
  pub:
    build:
      context: .
      dockerfile: ./pub/Dockerfile
    #command: tail -F anything  # prevents closure of container when no command is running

